###
POST http://localhost:3000/manhwas HTTP/1.1
content-type: application/json

{
    "title": "It Was a Mistake, Grand Duke!",
    "authors": ["joypyonn", "Sisse" ],
    "date": 2019,
    "manhwaStatus": "Ongoing",
    "genres": ["Romance", "Fantasy"],
    "url": "https://www.tappytoon.com/en/comics/it-was-a-mistake-grand-duke"

}


###
POST http://localhost:3000/register HTTP/1.1
content-type: application/json

{
    "username": "melkdy",
    "email": "c@asdf",
    "password": "hiii"
}

###
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "email": "katiemrussell28@gmail.com",
    "password": "K321741k!"
}

###
GET http://localhost:3000/refresh HTTP/1.1

###
GET http://localhost:3000/logout HTTP/1.1

###
POST http://localhost:3000/user HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImthdGllbXJ1c3NlbGwyOEBnbWFpbC5jb20iLCJpYXQiOjE2NTk2NjQ3NTksImV4cCI6MTY1OTY2NTM1OX0.iN1GLItxydtjjw35JsVmmnOTM21uBbFeaRTsUtU1mZA

{
    "email": "katiemrussell28@gmail.com"
}

###
POST http://localhost:3000/get-data HTTP/1.1
content-type: application/json

{
    "url": "https://www.tappytoon.com/en/comics/i-adopted-the-male-lead"
}

###
POST http://localhost:3000/one-manhwa HTTP/1.1
content-type: application/json

{
    "_id": "62eccb9468055a4b0d4d07c0"
}
###

POST http://localhost:3000/manhwas/filter HTTP/1.1
content-type: application/json


    {"genres": ["Fantasy","Romance"]}


###
POST http://localhost:3000/search HTTP/1.1
content-type: application/json

{ "title": "s" }


###
POST http://localhost:3000/reading-list/add HTTP/1.1
content-type: application/json

{
    "user": "katiemrussell28@gmail.com",
    "manhwa": "62eccb9468055a4b0d4d07c0"
}

###
POST http://localhost:3000/reading-list/remove HTTP/1.1
content-type: application/json

{
    "user": "katiemrussell28@gmail.com",
    "manhwa": "62eccb9468055a4b0d4d07c0"
}

###
GET http://localhost:3000/manhwas HTTP/1.1
content-type: application/json

{
    "genres": ["Romance"]
}


###
POST http://localhost:3000/check-list HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImthdGllbXJ1c3NlbGwyOEBnbWFpbC5jb20iLCJpYXQiOjE2NTk4NTE2NDQsImV4cCI6MTY1OTg1MjI0NH0.g-nW4ljB4j27RjoBFWDSkBlJ59VjaEImC00LzIHsfU8

{
    "email" : "katiemrussell28@gmail.com",
    "manhwa" : "62eccb9468055a4b0d4d07c0"
}


###
POST http://localhost:3000/reading-list HTTP/1.1
content-type: application/json

{
    "email" : "katiemrussell28@gmail.com"
}


###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "City Of God",
    "year": 2003,
    "language": "Portuguese"
}

###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "Parasite",
    "year": 2019,
    "language": "Korean"
}
