###
POST http://localhost:3000/manhwas HTTP/1.1
content-type: application/json

{
    "title": "Trash of the Counts Family",
    "image": "Trash-of-the-Counts-Family.jpg",
    "authors": ["Elegant Yoo Ryeo Han"],
    "date": 2019,
    "manhwaStatus": "Ongoing",
    "genres": ["Action", "Adventure", "Comedy", "Fantasy" ],
    "description": "When I opened my eyes, I was inside a novel.
[The Birth of a Hero].
[The Birth of a Hero] was a novel focused on the adventures of the main character, Choi Han, a high school boy who was transported to a different dimension from Earth, along with the birth of the numerous heroes of the continent.
I became a part of that novel as the tr*sh of the Counts family, the family that oversaw the territory where the first village that Choi Han visits is located.
The problem is that Choi Han becomes twisted after that village, and everyone in it, are destroyed by assassins.
The bigger problem is the fact that this s*upid tr*sh who Ive become doesnt know about what happened in the village and messes with Choi Han, only to get beaten to a pulp.
...This is going to be a problem.
I feel like something serious has happened to me.
But it was worth trying to make this my new life."
}


###
POST http://localhost:3000/new-user HTTP/1.1
content-type: application/json

{
    "username": "melky",
    "email": "c@a",
    "password": "hii"
}

###
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "email": "katiemrussell28@gmail.com",
    "password": "K321741k!"
}

###
GET http://localhost:3000/refresh HTTP/1.1

###
GET http://localhost:3000/logout HTTP/1.1

###
POST http://localhost:3000/user HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTk2MDQzMjYsImV4cCI6MTY1OTYwNDkyNn0.0rz0yUBIWS4i1QhJuJ9VHVAxh3X-qzi2mPXMFSLriyU

{
    "email": "katiemrussell28@gmail.com"
}
###
GET http://localhost:3000/manhwas HTTP/1.1

###

POST http://localhost:3000/manhwas/filter HTTP/1.1
content-type: application/json


    {"genres": ["Fantasy","Romance"]}


###
POST http://localhost:3000/search HTTP/1.1
content-type: application/json

{ "title": "s" }


###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "Eternal Sunshine Of The Spotless Mind",
    "year": 2004,
    "language": "English"
}

###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "High Fidelity",
    "year": 2000,
    "language": "English"
}

###
GET http://localhost:3000/manhwas HTTP/1.1
content-type: application/json

{
    "genres": ["Romance"]
}


###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "No Country For Old Men",
    "year": 2007,
    "language": "English"
}


###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "A Serious Man",
    "year": 2009,
    "language": "English"
}


###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "City Of God",
    "year": 2003,
    "language": "Portuguese"
}

###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "Parasite",
    "year": 2019,
    "language": "Korean"
}
